name: DebugRelease train

on:
  push:
    paths:
      - .github/workflows/debug_release_train.yml
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: installs
        run: sudo apt-get install musl-tools
      - uses: actions/checkout@v2
        with:
          repository: sourcegraph/sourcegraph
          path: sourcegraph
          ref: v3.26.0
      - name: build server
        env:
          VERSION: v3.26.0
          IMAGE: sourcegraph-server-oss
        run: |
          cd $GITHUB_WORKSPACE/sourcegraph/cmd/server
          ./pre-build.sh
          ./build.sh
