name: DebugRelease train

on:
  push:
    paths:
      - .github/workflows/debug_release_train.yml
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: installs
        run: sudo apt-get install musl-tools
      - uses: actions/checkout@v3
        with:
          repository: sourcegraph/sourcegraph
          path: sourcegraph
          ref: v3.26.1
      - uses: actions/setup-node@v3
        with:
          node-version: '^v16.0.7'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.16.2'
      - name: build server
        env:
          VERSION: v3.26.1
          IMAGE: sourcegraph-server-oss
        run: |
          cd $GITHUB_WORKSPACE/sourcegraph/cmd/server
          ./pre-build.sh
          ./build.sh
