name: DebugRelease train

on:
  push:
    paths:
      - .github/workflows/debug_release_train.yml
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: installs
        run: sudo apt-get install musl-tools
      - uses: actions/checkout@v2
        with:
          repository: sourcegraph/sourcegraph
          path: sourcegraph

  build_gitserver:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - run: |
         cd sourcegraph/cmd/gitserver
         ./build.sh
  build_searcher:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - run: |
          cd sourcegraph/cmd/searcher
          ./build.sh
  build_symbols:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - run: |
          cd sourcegraph/cmd/symbols
          ./build.sh
  build_frontend:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - run: |
          cd sourcegraph/cmd/frontend
          ./build.sh
  build_repo-updater:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - run: |
          cd sourcegraph/cmd/repo-updater
          ./build.sh
  build_server:
    runs-on: ubuntu-latest
    needs:
      - install
      - build_gitserver
      - build_searcher
      - build_symbols
      - build_frontend
      - build_repo-updater
    steps:
      - run: |
          cd sourcegraph/cmd/server
          ./pre-build.sh
          ./build.sh
