name: DebugRelease train

on:
  push:
    paths:
      - .github/workflows/debug_release_train.yml
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: installs
        run: sudo apt-get install musl-tools
      - uses: actions/checkout@v2
        with:
          repository: sourcegraph/sourcegraph
          path: sourcegraph
      - run: |
         cd $HOME/sourcegraph/cmd/gitserver
         ./build.sh
      - run: |
          cd $HOME/sourcegraph/cmd/searcher
          ./build.sh
      - run: |
          cd $HOME/sourcegraph/cmd/symbols
          ./build.sh
      - run: |
          cd $HOME/sourcegraph/cmd/frontend
          ./build.sh
      - run: |
          cd $HOME/sourcegraph/cmd/repo-updater
          ./build.sh
      - run: |
          cd $HOME/sourcegraph/cmd/server
          ./pre-build.sh
          ./build.sh
